### ISSUE TITLE
Add support for config file

### ISSUE THREAD

**Issue by engeir** [engeir/northern-lights-forecast#171]
To make it easier to install the project via `pip`/`pipx` and use all functionalities as intended it might be a good idea to look for config file in standard directories, e.g. `~/.config/nlf/config.ini`. [This](https://stackoverflow.com/questions/7567642/where-to-put-a-configuration-file-in-python) might be useful.

**Comment by RishiKumarRay** [comment]
config= None
for loc in os.curdir, os.path.expanduser("~"), "/etc/myproject", os.environ.get("MYPROJECT_CONF"):
    try: 
        with open(os.path.join(loc,"myproject.conf")) as source:
            config.readfp( source )
    except IOError:
        pass

you are working on something like this?

**Comment by engeir** [comment]
Maybe! Not sure, I havn't done something like that before, but the idea would be to be able to run it as a any other CLI, and have the telegram token be read from a config file placed in one of the typical places. For linux I guess `.config` is best, and macos as well, but for windows I'm not sure what the "best practice" is?

Actually, I guess `telegram-send` solves this in some other way that might be something to look into...

**Comment by engeir** [comment]
Might as well use the same as `telegram-send` since it's already a dependency, see line

https://github.com/rahiel/telegram-send/blob/2eb23bde734137b10da80fdf2e8a48d34f074454/telegram_send.py#L185
